
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const SET_LOADING= 'SET_LOADING';
// export const CLEAR_ERRORS = 'CLEAR_ERRORS';
// export const GET_ERRORS = 'GET_ERRORS';
// export const GET_EMAIL_ERRORS = 'GET_EMAIL_ERRORS';
// export const GET_PASSWORD_ERRORS = 'GET_PASSWORD_ERRORS';

// export const GET_LOGINWITHNUMIO_ERROR = 'GET_LOGINWITHNUMIO_ERROR';
// export const USER_LOGINWITHNUMIO = 'USER_LOGINWITHNUMIO';
// export const USER_LOGINWITHMETAMASK = 'USER_LOGINWITHMETAMASK'
// export const USER_SIGNUPWITHMETAMASK = 'USER_SIGNUPWITHMETAMASK'
// export const UPDATE_DAOATTRIBUTES = 'UPDATE_DAOATTRIBUTES'
